kind: Deployment
apiversion: apps/v1
metadata:
   name: webapp
spec:
   replicas: 2
   selector: #tells the controller which pods to match/belong to 
    matchLabels:
     app: webapp
   template:
      metadata:
        labels:
          app: webapp
      spec:
       containers:
        - name: webapp
          image: gjaguilar/pipeline_demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
    
